package de.thm.mni.mailsystem.model

import jakarta.persistence.*

/**
 * Represents a file attachment associated with a mail.
 *
 * Stores metadata and binary content of files attached to emails,
 * including name, type, size, and the actual file data as a BLOB.
 *
 * @property id Unique identifier for the attachment. Auto-generated by the database.
 * @property fileName The original name of the attached file.
 * @property mimeType The MIME type of the file (e.g., "application/pdf", "image/png").
 * @property size The size of the file in bytes.
 * @property data The binary content of the file stored as a BLOB.
 * @property mail The mail entity this attachment belongs to.
 */
@Entity
@Table(name = "attachments")
class Attachment(
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false)
    val fileName: String,

    @Column(nullable = false)
    val mimeType: String,

    @Column(nullable = false)
    val size: Long, // Size in bytes

    @Lob
    @Column(columnDefinition = "BLOB")
    @com.fasterxml.jackson.annotation.JsonIgnore
    var data: ByteArray? = null,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mail_id")
    @com.fasterxml.jackson.annotation.JsonIgnore
    var mail: Mail? = null
)