package de.thm.mni.mailsystem.model

import jakarta.persistence.*

/**
 * Domain entity representing a file attachment associated with a mail.
 *
 * ## Architecture Role (3-Tier Spring Boot Application)
 *
 * **Layer Classification:** Domain Model (Persistent Entity) Layer
 *
 * This entity represents the structural mapping between:
 * - **Domain Logic:** File attachments are related to `Mail` entities (many-to-one)
 * - **Persistence:** Maps to "attachments" table in H2 database
 * - **ORM:** Hibernate manages object-relational mapping lifecycle
 *
 * ## Attachment Lifecycle
 *
 * **Creation:** Uploaded by user to a DRAFT mail via [MailService.uploadAttachment]
 * **Storage:** Binary content stored as BLOB, metadata in table columns
 * **Deletion:** Removed along with mail via cascade delete or directly via [MailService.deleteAttachment]
 * **Immutability:** Cannot be modified once mail is sent (only DRAFT mails can be modified)
 *
 * ## Lazy Loading Strategy
 *
 * **Fetch Type:** LAZY on many-to-one relationship (default for @ManyToOne is EAGER, overridden here)
 * **Binary Data:** ByteArray (BLOB) loaded only when explicitly accessed
 * **Performance:** Reduces memory footprint for mail list operations
 * **Safety:** @Transactional boundary keeps Hibernate session open during access
 *
 * ## JSON Serialization
 *
 * Properties marked with @JsonIgnore prevent:
 * - Binary content in JSON responses (@JsonIgnore on [data])
 * - Circular references between Mail and Attachment (@JsonIgnore on [mail])
 * - Infinite recursion in serialization (Mail → Attachments → Mail → ...)
 *
 * @property id Unique primary key, auto-generated by database sequence
 * @property fileName Original filename from user upload (e.g., "report.pdf", "image.jpg")
 * @property mimeType MIME type (RFC 2045) indicating file format for browser handling
 * @property size File size in bytes for UI display and bandwidth estimation
 * @property data Binary file content stored as BLOB, nullable due to lazy loading
 * @property mail The parent mail entity this attachment belongs to (many-to-one relationship)
 *
 * @see Mail
 * @see Attachment.id
 */
@Entity
@Table(name = "attachments")
class Attachment(
    /**
     * Unique identifier for the attachment record.
     *
     * **Generation Strategy:** IDENTITY (auto-increment by database)
     * **Primary Key:** Uniquely identifies this attachment across all attachments
     * **Default:** null during object creation, set by database on INSERT
     * **Nullable:** Before persistence; non-null after
     */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    /**
     * Original filename provided by the user at upload time.
     *
     * **Source:** [MultipartFile.originalFilename] from HTTP multipart form
     * **Examples:** "report.pdf", "screenshot.png", "archive.zip"
     * **Fallback:** Defaults to "unknown" if not provided by client
     * **Usage:** Set in Content-Disposition HTTP header for download
     * **Constraint:** NOT NULL - every attachment must have a filename
     */
    @Column(nullable = false)
    val fileName: String,

    /**
     * MIME type (RFC 2045) indicating the file format.
     *
     * **Source:** [MultipartFile.contentType] from HTTP multipart form
     * **Format:** type/subtype (e.g., "application/pdf", "image/jpeg", "text/plain")
     * **Examples:**
     * - "application/pdf" - PDF document
     * - "image/jpeg" - JPEG image
     * - "application/zip" - ZIP archive
     * - "text/plain" - Plain text file
     * - "application/octet-stream" - Unknown binary format (fallback)
     * **Usage:** Set in Content-Type HTTP header for download
     * **Constraint:** NOT NULL - every file has a type
     */
    @Column(nullable = false)
    val mimeType: String,

    /**
     * File size in bytes.
     *
     * **Source:** [MultipartFile.size] property
     * **Range:** 0 to ~2GB (H2 BLOB limit in typical configurations)
     * **Usage:**
     * - Validation (reject empty files, enforce size limits)
     * - UI display (show "2.5 MB" to user)
     * - HTTP header Content-Length
     * - Bandwidth estimation
     * **Constraint:** NOT NULL - must always be recorded
     */
    @Column(nullable = false)
    val size: Long,

    /**
     * Binary file content stored as BLOB (Binary Large Object).
     *
     * **Storage:** H2 database BLOB column (supports up to 2GB)
     * **Type:** ByteArray (Kotlin primitive byte array, Java byte[])
     * **Nullability:** Optional due to lazy loading strategy
     *
     * **Lazy Loading Details:**
     * - @Lob annotation: Tells Hibernate this is a large object
     * - Assignment: `fetch = FetchType.LAZY` is default for LOBs
     * - Behavior: NOT loaded when Mail is fetched; loaded only when accessed
     * - Session: Requires active @Transactional boundary to access safely
     *
     * **JSON Handling:**
     * - @JsonIgnore prevents serialization of binary data to JSON
     * - Reason: ByteArray cannot be safely represented in JSON
     * - Alternative: Binary served via dedicated download endpoint
     *
     * **Memory Efficiency:**
     * - Mail list query loads only metadata (1 MB for 1000 mails)
     * - Binary not loaded unless user clicks "download"
     * - Prevents out-of-memory on large mail systems
     *
     * **Default:** null during object creation; populated on upload
     */
    @Lob
    @Column(columnDefinition = "BLOB")
    @com.fasterxml.jackson.annotation.JsonIgnore
    var data: ByteArray? = null,

    /**
     * Many-to-One relationship: Multiple attachments belong to one mail.
     *
     * **Relationship Semantics:**
     * - Cardinality: Many Attachments → One Mail
     * - Required: Every attachment must belong to exactly one mail
     * - Direction: Owned side (child) of bidirectional relationship
     * - Cascade: Deletion of mail cascades to attachments (orphanRemoval = true on parent)
     *
     * **Lazy Loading:**
     * - @ManyToOne(fetch = FetchType.LAZY): Mail not loaded when attachment is fetched
     * - Efficiency: Avoids loading entire parent when only child metadata needed
     * - Pattern: Opposite of @OneToMany which defaults to EAGER
     *
     * **Foreign Key Mapping:**
     * - @JoinColumn(name = "mail_id"): Column name in attachments table
     * - References Mail.id (implicit by convention)
     * - NOT NULL constraint enforced at database level
     * - Referential integrity: Cannot have orphaned attachments
     *
     * **JSON Handling:**
     * - @JsonIgnore prevents serialization of Mail object
     * - Reason: Prevents circular references (Mail → Attachments → Mail → ...)
     * - Also: Prevents unnecessary parent object in child response
     *
     * **Bidirectional Management:**
     * - Parent side: Mail.attachments: MutableList<Attachment>
     * - Child side: Attachment.mail: Mail?  ← you are here
     * - Maintenance: Via [Mail.addAttachment] method (maintains both references)
     *
     * **Access Pattern (in Service):**
     * ```kotlin
     * val mail = mailRepository.findById(mailId)  // Mail fetched, attachments LAZY
     * val attachment = mail.attachments.find { ... }  // Now attachments loaded from DB
     * val data = attachment.data  // ByteArray BLOB loaded separately
     * ```
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mail_id")
    @com.fasterxml.jackson.annotation.JsonIgnore
    var mail: Mail? = null
)