package de.thm.mni.mailsystem.model

import jakarta.persistence.*
import com.fasterxml.jackson.annotation.JsonIgnore

/**
 * Represents a recipient of a mail.
 *
 * Each recipient has an email address and a type (TO, CC, BCC, or REPLY_TO)
 * indicating how they are included in the mail.
 *
 * @property id Unique identifier for the recipient. Auto-generated by the database.
 * @property address The email address of the recipient.
 * @property type The type of recipient (TO, CC, BCC, or REPLY_TO).
 * @property mail The mail entity this recipient is associated with.
 */
@Entity
@Table(name = "mail_recipients")
class MailRecipient(
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false)
    val address: String, // The mail address

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    val type: RecipientType, // TO, CC, BCC, or REPLY_TO

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mail_id")
    @JsonIgnore
    var mail: Mail? = null
)

/**
 * Enumeration of recipient types for mail delivery.
 *
 * @property TO Primary recipient of the mail.
 * @property CC Carbon copy recipient (visible to all recipients).
 * @property BCC Blind carbon copy recipient (hidden from other recipients).
 * @property REPLY_TO Address to which replies should be sent.
 */
enum class RecipientType { TO, CC, BCC, REPLY_TO }