package de.thm.mni.mailsystem.model

import jakarta.persistence.*
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Size
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp
import java.time.LocalDateTime

/**
 * Represents an email entity in the mail system.
 *
 * This entity manages all aspects of an email including its content, recipients,
 * attachments, and lifecycle status (draft, sent, error).
 *
 * @property id Unique identifier for the mail. Auto-generated by the database.
 * @property sender The email address of the sender (from field).
 * @property subject The subject line of the email.
 * @property content The plain text content body of the email.
 * @property status Current status of the mail (DRAFT, SENT, or ERROR). Defaults to DRAFT.
 * @property source Origin of the mail, either INTERN (internal system) or EXTERN (external source).
 * @property createdAt Timestamp when the mail was created. Auto-generated and immutable.
 * @property updatedAt Timestamp when the mail was last modified. Auto-updated on changes.
 * @property sentAt Timestamp when the mail was successfully sent. Null for unsent mails.
 */
@Entity
@Table(name = "mails")
class Mail(
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @field:NotBlank(message = "Sender is required")
    @Column(nullable = false)
    var sender: String, // "From" field

    @field:NotBlank(message = "Subject is required")
    @field:Size(max = 255, message = "Subject must be at most 255 characters")
    @Column(nullable = false)
    var subject: String,

    @field:NotBlank(message = "Content is required")
    @Column(columnDefinition = "TEXT")
    var content: String, // Plain text content of the mail

    @Enumerated(EnumType.STRING)
    var status: MailStatus = MailStatus.DRAFT, // Initially draft

    @Enumerated(EnumType.STRING)
    @Column(updatable = false)
    val source: MailSource, // intern or extern

    @CreationTimestamp
    @Column(updatable = false)
    val createdAt: LocalDateTime? = null, // Local creation time

    @UpdateTimestamp
    val updatedAt: LocalDateTime? = null, // Auto-updated on modification

    var sentAt: LocalDateTime? = null // Initially not set
) {

    /**
     * Enumeration of possible mail statuses.
     *
     * @property DRAFT Mail is in draft state and can be edited.
     * @property SENT Mail has been successfully sent.
     * @property ERROR Mail transmission failed.
     */
    enum class MailStatus { DRAFT, SENT, ERROR }

    /**
     * Enumeration of mail origin sources.
     *
     * @property INTERN Mail originated from within the system.
     * @property EXTERN Mail originated from an external source.
     */
    enum class MailSource { INTERN, EXTERN }

    /**
     * List of recipients associated with this mail.
     *
     * Managed with cascade operations - recipients are saved and deleted with the mail.
     * Uses EAGER fetch to avoid lazy loading issues when serializing to JSON.
     */
    @OneToMany(mappedBy = "mail", cascade = [CascadeType.ALL], orphanRemoval = true, fetch = FetchType.EAGER)
    val recipients: MutableList<MailRecipient> = mutableListOf()

    /**
     * List of file attachments associated with this mail.
     *
     * Managed with cascade operations - attachments are saved and deleted with the mail.
     * Uses EAGER fetch to avoid lazy loading issues when serializing to JSON.
     */
    @OneToMany(mappedBy = "mail", cascade = [CascadeType.ALL], orphanRemoval = true, fetch = FetchType.EAGER)
    val attachments: MutableList<Attachment> = mutableListOf()

    /**
     * Adds a recipient to this mail and maintains the bidirectional relationship.
     *
     * @param recipient The mail recipient to add to this mail.
     */
    fun addRecipient(recipient: MailRecipient) {
        recipients.add(recipient)
        recipient.mail = this
    }

    /**
     * Adds an attachment to this mail and maintains the bidirectional relationship.
     *
     * @param attachment The attachment to add to this mail.
     */
    fun addAttachment(attachment: Attachment) {
        attachments.add(attachment)
        attachment.mail = this
    }
}