package de.thm.mni.mailsystem.model

import jakarta.persistence.*

/**
 * Represents a user account in the mail system.
 *
 * This entity manages user authentication credentials and serves as the
 * foundation for JWT-based authentication. Users authenticate using their
 * username (email address) and password.
 *
 * @property id Unique identifier for the user. Auto-generated by the database.
 * @property firstname The user's first name.
 * @property lastname The user's last name.
 * @property mail The user's email address, used for login and mail operations. Must be unique.
 * @property passwordHash The BCrypt-hashed password. Never store passwords in plain text.
 */
@Entity
@Table(name = "app_users") // 'user' is often a reserved word in SQL
class User(
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false)
    val firstname: String,

    @Column(nullable = false)
    val lastname: String,

    @Column(unique = true, nullable = false)
    val mail: String,

    @Column(nullable = false)
    val passwordHash: String
)